### ISSUE TITLE
API endpoint no longer exists?

### ISSUE THREAD

**Issue by JScheire** [neonipun/notify-ikea-click-n-collect#1]
https://github.com/neonipun/notify-ikea-click-n-collect/blob/5608a8e3f44f6c4eeeed2c6b7ea7cb3069de0e9e/ikea-stores-notification.py#L32

This request returns status code 404, maybe it no longer exists?

**Comment by neonipun** [comment]
Thats true. Just looked at it and it changed to https://api.ikea-status.dong.st/prod/locations. 
In the meantime, @JScheire do you want to change it, make it work and do a PR?? I'll try to work around it this weekend.

**Comment by JScheire** [comment]
Yeah I can look into it.

**Comment by neonipun** [comment]
Issue fixed with PR #2
